### ISSUE TITLE
CAPTCHA 

### ISSUE THREAD

**Issue by Ozakinn** [minhduc29/Discord-Automation#1]
I used this on my raspbberry pi, Discord detect gives me Captcha to verify. Cant bypass it using this tool.

**Comment by Ozakinn** [comment]
Nvm, i do it manually. Good work for this Dev. All is good now. I though it can also bypass the captcha autoamtically.

**Comment by minhduc29** [comment]
> I used this on my raspberry pi, Discord detect gives me Captcha to verify. Cant bypass it using this tool.

Captcha was created to verify humans, authorities and prevent tools like this. Sometimes you need to log in by yourself for the first few times and discord won't ask you to verify more or you can change the code to make the sleep time longer so that you can do it by yourself without interrupting the program. Selenium was initially used for web-based auto testing but I used it for a different purpose. I don't really know about raspberry pi so you may have to change the code or use a different repo for reference. As I've written in README, this is just a demonstration of some ideas that use Selenium to automate certain boring and repetitive tasks. This works for me and some others but of course not for everyone. Think and solve it yourself. The issue is you, not this repo.
